name: urdu_plagiarism_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  file_picker: ^10.1.9
  open_filex: ^4.7.0
  dio: ^5.8.0+1
  lottie: ^3.3.1
  path_provider: ^2.1.5
  mime: ^2.0.0
  http_parser: ^4.1.2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/plag_logo.png"
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/plag_logo.jpg
    - assets/plag_logo.png
